### ISSUE TITLE
How to set a mint price for Layerzero contrcts?

### ISSUE THREAD

**Issue by ikhub** [specialOne-coder/LayerZero-Interoperable-Nft#1]
The contract mints the NFTs for free. Is there any way deployer can set a mint fee?

**Comment by specialOne-coder** [comment]
Hey, hope you're doing good.
First of all, I'd like to remind you that my contract may be out of date, so don't hesitate to check for the latest layerzero update.

 I don't have the exact context of your project, but if you want to add a mint price, just add this line 

-  New contract variable : 
 `uint public mintPrice = 1 ether; //your price`
 you'll need to add a function for modify the price if you want the owner to set a mint fee : 
 
 ```
function setFee(uint _newEthAmount) public onlyOwner {
      mintPrice = _newEthAmount
 }

```
- Add requirement in `mint` function : 
`require(msg.value >= mintPrice, "NOT_ENOUGH_ETH");`
If you wanna accept a token  instead of ETH you'll need to use IERC20 interface.

**Comment by ikhub** [comment]
Thank you sir. Will try them and test.
